# main text of home
name: STEPHANIE LÓPEZ
bio: Una chica tranquila y buena persona
# twitter summary info
description: Un blog sobre mi

picture: estefani.jpeg   estefani2.jpeg estefani3.jpeg estefani4.jpeg estefani6.jpeg tulipan.webp estefani7.jpeg


url: http://koppl.in/violet
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: Estefani Lopez 
instagram: estef.lop07
github: mygithub
email: 250300621@ucaribe.edu.mx

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
